### ISSUE TITLE
Doesn't fix for installed apk

### ISSUE THREAD

**Issue by liudongmiao** [Tungstwenty/FakeIDFix#1]
As the apk's signatures is cached in `/data/system/packages.xml`, so when the apk is not changed, the signatures (via the api `getPackageInfo`) will returns the cached values. And unfortunately, Bluebox Security Scanner cannot scan out the apk. There is a poc apk here: https://github.com/retme7/FakeID_poc_by_retme_bug_13678484/, You can install it before the fake-id-fix, then active this module and get the signatures via `getPackageInfo` , it will return two signatures.

For me, I hack the `loadCertificates` to avoid the usage of `ThreadLocal`, and hack `generatePackageInfo` to check `signatures` again. As normally, there is only `one` certificate, so there is only `one` signatures, although it's not cached, but it's more safe.

For the source of mine, please visit here: https://github.com/liudongmiao/MasterKeyFixGB/blob/master/src/me/piebridge/masterkeyfixgb/XposedMod.java

**Comment by Tungstwenty** [comment]
I am aware of this behavior, yes.

Please check this post: http://forum.xda-developers.com/xposed/modules/mod-fakeid-vulnerability-fix-t2833854/post54629369
It is also a PoC with multiple signatures, and it will scan the entire system for packages with multiple signatures, stating whether each certificate has signed the previous one.
But it doesn't take the Subject / Issuer into account, and it appears that there are some situations where multiple signers are present, and they don't form a chain (nor do they claim to).
Check this example: http://forum.xda-developers.com/showpost.php?p=54630063&postcount=46 and also this one http://forum.xda-developers.com/showpost.php?p=54632966&postcount=53 where AdBlockAddon is issued with 2 independent signers.

About your patch: in the latest version of my mod, I'm only changing the behavior to include the check if it's running on the system process. Since Google didn't change the behavior in JarTools to always enforce the check, I'm guessing that it might cause compatibility issues to always do it.

**Comment by liudongmiao** [comment]
I don't know why the `FakeIDCheck-1.1.apk` cannot be installed on gb device, said that there is no certificate for `res/layout/main.xml`.

As `PackageParse` is hidden in the sdk, so I didn't think any package can call it except PackageManager service.

I have update the patch, will work for multi certificate. 

BTW, did you know why the FakeID doesn't exist in the android l preview? The code in l-preview is the same with non-patched version.

**Comment by Tungstwenty** [comment]
I also don't understand why isn't the FakeID vulnerability present on the L preview, since the commit https://android.googlesource.com/platform/libcore/+/2bc5e811a817a8c667bca4318ae98582b0ee6dc6 isn't present there.
But I also don't know what additional changes exist apart from that one, on ROMs that have it fixed, since the commit by itself only provides an additional, non-default behavior for strictly validating issuers.

I think your patch might still be vulnerable.
If you have 3 certificates such as:
(Subject:CompanyA, Issuer:CompanyB) + (Subject:CompanyB, Issuer:CompanyC) + (Subject:CompanyC, Issuer:CompanyC)
and the 2nd one is rejected by your getCertificates method because it didn't sign the first one, the last one will still be added even if it didn't sign the 2nd one.

But on the other hand, the 3rd certificate should be included it if did sign the jar directly, which some of the examples I mentioned earlier have.

**Comment by liudongmiao** [comment]
Thanks for your example. I will remove it.

Very strange, the emulator in l-preview seems that the codes in the sdk are not the same with the source  in aosp..

For example, there are following methods:

```
private static [[Ljava.security.cert.Certificate; android.content.pm.PackageParser.loadCertificates(java.util.jar.StrictJarFile,java.util.zip.ZipEntry,byte[])
```

in aosp, it returns `Certificate[]` instead of `Certificate[][]`. Furthermore, there is another method `convertToSignatures`:

```
private static [Landroid.content.pm.Signature; android.content.pm.PackageParser.convertToSignatures(java.security.cert.Certificate[][]) throws java.security.cert.CertificateEncodingException
```
